BEGIN;
	CREATE SCHEMA IF NOT EXISTS crypto;

	CREATE TABLE IF NOT EXISTS crypto.coins (
	id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    cost NUMERIC(18, 8) NOT NULL,
    actual_at TIMESTAMP NOT NULL DEFAULT NOW()
);
END;
