// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	entities "cryptorates/coin/internal/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ActualizeRates mocks base method.
func (m *MockService) ActualizeRates(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActualizeRates", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActualizeRates indicates an expected call of ActualizeRates.
func (mr *MockServiceMockRecorder) ActualizeRates(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActualizeRates", reflect.TypeOf((*MockService)(nil).ActualizeRates), ctx)
}

// GetActualRates mocks base method.
func (m *MockService) GetActualRates(ctx context.Context, titles []string) ([]*entities.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActualRates", ctx, titles)
	ret0, _ := ret[0].([]*entities.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActualRates indicates an expected call of GetActualRates.
func (mr *MockServiceMockRecorder) GetActualRates(ctx, titles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActualRates", reflect.TypeOf((*MockService)(nil).GetActualRates), ctx, titles)
}

// GetAggregateRates mocks base method.
func (m *MockService) GetAggregateRates(ctx context.Context, titles []string, aggregation string) ([]*entities.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregateRates", ctx, titles, aggregation)
	ret0, _ := ret[0].([]*entities.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregateRates indicates an expected call of GetAggregateRates.
func (mr *MockServiceMockRecorder) GetAggregateRates(ctx, titles, aggregation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregateRates", reflect.TypeOf((*MockService)(nil).GetAggregateRates), ctx, titles, aggregation)
}
