// Code generated by MockGen. DO NOT EDIT.
// Source: rates_source.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	entities "cryptorates/coin/internal/entities"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRatesSource is a mock of RatesSource interface.
type MockRatesSource struct {
	ctrl     *gomock.Controller
	recorder *MockRatesSourceMockRecorder
}

// MockRatesSourceMockRecorder is the mock recorder for MockRatesSource.
type MockRatesSourceMockRecorder struct {
	mock *MockRatesSource
}

// NewMockRatesSource creates a new mock instance.
func NewMockRatesSource(ctrl *gomock.Controller) *MockRatesSource {
	mock := &MockRatesSource{ctrl: ctrl}
	mock.recorder = &MockRatesSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatesSource) EXPECT() *MockRatesSourceMockRecorder {
	return m.recorder
}

// GetRequestData mocks base method.
func (m *MockRatesSource) GetRequestData(ctx context.Context, titles []string, costIn string) (string, string, io.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestData", ctx, titles, costIn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(io.Reader)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetRequestData indicates an expected call of GetRequestData.
func (mr *MockRatesSourceMockRecorder) GetRequestData(ctx, titles, costIn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestData", reflect.TypeOf((*MockRatesSource)(nil).GetRequestData), ctx, titles, costIn)
}

// ParseResponseData mocks base method.
func (m *MockRatesSource) ParseResponseData(ctx context.Context, body io.Reader, costIn string) ([]*entities.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseResponseData", ctx, body, costIn)
	ret0, _ := ret[0].([]*entities.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseResponseData indicates an expected call of ParseResponseData.
func (mr *MockRatesSourceMockRecorder) ParseResponseData(ctx, body, costIn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseResponseData", reflect.TypeOf((*MockRatesSource)(nil).ParseResponseData), ctx, body, costIn)
}
